### ISSUE TITLE
Error requesting reviewer: Unprocessable Entity (HTTP 422)

### ISSUE THREAD

**Issue by sudipto1988** [repo-sync/pull-request#137] opened 2023-04-07 17:42 UTC
Hi Team,

Even we have correct reviewers list in the github action secerts, we are getting below error intermitantly. When we rerun the job, it runs fine. If anyone can look into this issue will be helpfull.

✖ Pull request command failed. This is the stderr output:
  Error requesting reviewer: Unprocessable Entity (HTTP 422)
  Reviews may only be requested from collaborators. One or more of the users or teams you specified is not a collaborator of the

**Comment by theletterf** [comment] 2023-05-09 08:23
This is a duplicate of https://github.com/repo-sync/pull-request/issues/119

**Comment by heiskr** [comment] 2023-06-12 17:54
Thank you for opening this issue. Per the updated README, we are in process of archiving this repository, and encourage using [`gh pr create`](https://cli.github.com/manual/gh_pr_create) directly in your workflows instead.

**Closed by heiskr** 2023-06-12 17:54 UTC

**Comment by theletterf** [comment] 2023-06-13 08:05
@heiskr The README example is incomplete. `pull-request` allowed to update existing sync PRs; this is not the case with `gh pr create`.
